-- ═══════════════════════════════════════════════════════════════════════
-- omo — SCHEMA SYNC
-- ═══════════════════════════════════════════════════════════════════════
--
-- WHAT THIS IS
--   Schema drift catch-up. Over time, changes were made directly in the
--   Kura Supabase SQL Editor and never written back into MIGRATION.sql or
--   MIGRATION_V2.sql. This file contains ONLY the DDL that exists in the
--   live database but was missing from the committed migrations, so that
--   the repo can recreate the database from scratch.
--
--   Generated by introspecting the live Kura schema (project lrbmtcyhqzuyczovajnj)
--   on 2026-07-18. Reflects live state as of that date.
--
-- WHAT IT COVERS
--   1. omo_options.lat / .lng            — coordinate display columns
--   2. omo_criteria.is_visit_rated       — flags criteria shown in the review form
--   3. The reviews subsystem, which had NO committed DDL at all:
--        omo_reviewers, omo_reviews, omo_review_ratings, omo_review_photos
--      plus their RLS enablement and policies.
--
--   omo_versions IS already committed in MIGRATION.sql and is NOT repeated here.
--
-- HOW TO RUN
--   Run AFTER MIGRATION.sql and MIGRATION_V2.sql. Paste into the Supabase
--   SQL editor.
--
--   Fully idempotent and additive-only: every statement is guarded with
--   IF NOT EXISTS / IF EXISTS. On the existing live database this is a
--   no-op — it creates nothing and drops no data. On a fresh rebuild it
--   supplies the missing pieces. Safe to run repeatedly.
--
--   Schema only. No seed or user data.
--
-- ── KNOWN DIVERGENCE, NOT FIXED HERE (read this) ───────────────────────
--   MIGRATION_V2.sql appears to have NEVER been applied to the live
--   database. As of 2026-07-18 the live schema is MISSING:
--     • omo_rankings.chosen_option_id
--     • omo_rankings.outcome
--     • the widened category check allowing 'coffee' and 'restaurants'
--       (live constraint still only allows life/apartments/travel/gear/other)
--   That is drift in the opposite direction — the repo is ahead of the DB,
--   not behind it. It is deliberately NOT reproduced here, because that DDL
--   is already committed. Fix it by running MIGRATION_V2.sql against live.
-- ═══════════════════════════════════════════════════════════════════════


-- ── 1. omo_options: coordinates ────────────────────────────────────────
-- Rendered as decorative coordinate text on the option card when present.

alter table omo_options add column if not exists lat numeric(10,6);
alter table omo_options add column if not exists lng numeric(10,6);


-- ── 2. omo_criteria: review-form participation ─────────────────────────
-- Marks which criteria appear as star-rating rows in the review form.

alter table omo_criteria add column if not exists
  is_visit_rated boolean not null default true;


-- ── 3. REVIEWS SUBSYSTEM ───────────────────────────────────────────────
-- Living rankings: places judged over time via the Reviews tab.
-- Created in the SQL editor; no committed DDL existed before this file.
-- Ordered so foreign-key dependencies are satisfied.

-- 3a. Reviewers — device identity, not an auth boundary.
-- The omo_reviewer_id cookie (see src/lib/identity.ts) maps to a row here.
create table if not exists omo_reviewers (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  color      text not null,
  created_at timestamptz not null default now()
);

-- 3b. Reviews — one per (option, reviewer).
create table if not exists omo_reviews (
  id           uuid primary key default gen_random_uuid(),
  option_id    uuid not null references omo_options(id)   on delete cascade,
  reviewer_id  uuid not null references omo_reviewers(id) on delete cascade,
  vibe         text not null check (vibe in ('loved','liked','nope')),
  note         text,
  submitted_at timestamptz not null default now(),
  unique (option_id, reviewer_id)
);

-- 3c. Per-criterion star ratings attached to a review (1–5).
create table if not exists omo_review_ratings (
  id           uuid primary key default gen_random_uuid(),
  review_id    uuid not null references omo_reviews(id)  on delete cascade,
  criterion_id uuid not null references omo_criteria(id) on delete cascade,
  stars        integer not null check (stars >= 1 and stars <= 5),
  unique (review_id, criterion_id)
);

-- 3d. Photos attached to a review.
-- Read and rendered by the app; rows are inserted out-of-band (no upload path).
create table if not exists omo_review_photos (
  id           uuid primary key default gen_random_uuid(),
  review_id    uuid not null references omo_reviews(id) on delete cascade,
  storage_path text not null,
  caption      text,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);


-- ── 4. RLS ─────────────────────────────────────────────────────────────
-- Enabling RLS is idempotent in Postgres — re-running is a no-op.

alter table omo_reviewers      enable row level security;
alter table omo_reviews        enable row level security;
alter table omo_review_ratings enable row level security;
alter table omo_review_photos  enable row level security;


-- ── 5. POLICIES ────────────────────────────────────────────────────────
-- Matching live exactly: permissive, role `public`.
-- Reads are unconditional. Anon INSERT is allowed on reviews, ratings and
-- photos (the app's only client-side write path is submitReview).
--
-- NOTE: live has NO insert policy on omo_reviewers — reviewer rows are
-- seeded by hand in the SQL editor. Reproduced faithfully; do not add one
-- without deciding that is what you want.

drop policy if exists "anon read reviewers" on omo_reviewers;
create policy "anon read reviewers" on omo_reviewers
  for select using (true);

drop policy if exists "anon read reviews" on omo_reviews;
create policy "anon read reviews" on omo_reviews
  for select using (true);

drop policy if exists "anon write reviews" on omo_reviews;
create policy "anon write reviews" on omo_reviews
  for insert with check (true);

drop policy if exists "anon read review_ratings" on omo_review_ratings;
create policy "anon read review_ratings" on omo_review_ratings
  for select using (true);

drop policy if exists "anon write review_ratings" on omo_review_ratings;
create policy "anon write review_ratings" on omo_review_ratings
  for insert with check (true);

drop policy if exists "anon read review_photos" on omo_review_photos;
create policy "anon read review_photos" on omo_review_photos
  for select using (true);

drop policy if exists "anon write review_photos" on omo_review_photos;
create policy "anon write review_photos" on omo_review_photos
  for insert with check (true);


-- ── 6. NOT INCLUDED: omo_visit_ratings ─────────────────────────────────
-- src/lib/supabase.ts references a table `omo_visit_ratings` in
-- getVisitRatings() (line ~180) and upsertVisitRating() (line ~196).
-- THAT TABLE DOES NOT EXIST in the live database.
--
-- No DDL is invented for it here. Both functions are exported but never
-- called anywhere in src/, so nothing currently fails at runtime — it is
-- dead code left over from a superseded design, replaced by the
-- omo_reviews subsystem above. The fix is to delete those two functions
-- (plus the OmoVisitRating interface and the Vibe / Rater types, if they
-- have no other consumers), NOT to create the table.
-- ═══════════════════════════════════════════════════════════════════════
